$script = <<-SCRIPT
sudo apt update -y && sudo apt upgrade -y
sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
sudo systemctl restart sshd
sudo reboot
SCRIPT

Vagrant.configure("2") do |config|
    # Define the number of VMs
    num_vms = 4

    # Define a base IP Address
    base_ip = "192.168.33."

    # Loop to define VMs
    (1..num_vms).each do |i|
        config.vm.define "ubuntu-#{i}" do |vm|
            vm.vm.box = "ubuntu/bionic64"
            vm.vm.network  "private_network",
                ip: "#{base_ip}#{100 + i}"
            vm.vm.hostname = "ubuntu-#{i}"
            vm.vm.provision "shell", inline: $script
            vm.vm.boot_timeout = 600

            vm.vm.provider "virtualbox" do |v|
                # customize virtual machine settings if needed
                v.memory = 2046
                # v.cpu = 2
            end
        end
    end
end