Vagrant.configure("2") do |config|
  
    # Define the number of VMs you want
    num_vms = 3
    
    # Define a base IP address
    base_ip = "192.168.33."
    
    # Loop to define VMs
    (1..num_vms).each do |i|
      config.vm.define "ubuntu#{i}" do |vm|
        vm.vm.box = "ubuntu/bionic64"
        vm.vm.network "private_network", ip: "#{base_ip}#{100 + i}"
        vm.vm.hostname = "ubuntu#{i}"
        
        # Specify VirtualBox as the provider
        vm.vm.provider "virtualbox" do |v|
          # Customize virtual machine settings if needed
          v.memory = 2048
          v.cpus = 2
        end
      end
    end
  
  end